SUMMARY = "A Python Slugify application that handles Unicode"
SECTION = "devel/python"
HOMEPAGE = "https://github.com/un33k/python-slugify"
LICENSE = "MIT"

LIC_FILES_CHKSUM = "file://LICENSE;md5=7946d011d653bfcfbb24480377867128"

SRC_URI[md5sum] = "e935c1c9bd553756edab4a35b7c35701"
SRC_URI[sha256sum] = "5dbb360b882b2dabe0471a1a92f604504d83c2a73c71f2098d004ab62e695534"

PYPI_PACKAGE = "python-slugify"
inherit pypi
