SUMMARY = "ASCII transliterations of Unicode text."
SECTION = "devel/python"
HOMEPAGE = "https://pypi.org/project/Unidecode/"
LICENSE = "GPL2+"
LIC_FILES_CHKSUM = "file://LICENSE;md5=b234ee4d69f5fce4486a80fdaf4a4263"

PYPI_PACKAGE = "Unidecode"
inherit pypi

SRC_URI[md5sum] = "2282cfe97e1b8a2b27ce2f4ab57dc4e5"
SRC_URI[sha256sum] = "8b85354be8fd0c0e10adbf0675f6dc2310e56fda43fa8fe049123b6c475e52fb"

