SUMMARY = "Wrapper library for accessing the language model tools for CMU Sphinx (CMUCLMTK)."
SECTION = "devel/python"
HOMEPAGE = "https://github.com/Holzhaus/python-cmuclmtk"
LICENSE = "BSD"

LIC_FILES_CHKSUM = "file://PKG-INFO;md5=ddb174f5dc0e043e7793ab5efe4ce4f5"

SRC_URI[md5sum] = "87a2e2bf1f08a51509df558d7ad72def"
SRC_URI[sha256sum] = "62d284f64965fe8675b29fab7072af0b046732d9e99e2f1f0be7324f3f72fac5"

PYPI_PACKAGE = "cmuclmtk"
inherit pypi
